### ISSUE TITLE
ModuleNotFoundError: No module named 'pretrainedmodels'

### ISSUE THREAD

**Issue by happog** [Vipermdl/OCR_detection_IC15#3]
python eval.py
Traceback (most recent call last):
  File "eval.py", line 10, in <module>
    from model.model import FOTSModel
  File "/Users/zakj/Desktop/work/detection_fots/model/model.py", line 6, in <module>
    import pretrainedmodels as pm
ModuleNotFoundError: No module named 'pretrainedmodels'

**Comment by pankaj-pundir** [comment]
Whats the fix of this issue ??
EDIT:
`pip install pretrainedmodels`
